# Generated by Django 4.2.2 on 2023-06-30 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DictionaryVal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=1)),
                ('value', models.CharField(db_index=True, max_length=2)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lagushki.dictionary')),
            ],
        ),
    ]
