# Generated by Django 4.2.2 on 2023-07-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_user_birth_date_alter_user_passport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
