# Generated by Django 4.2.2 on 2023-07-28 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_user_phone_alter_user_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='car_id',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='order',
            name='car_mark',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='order',
            name='car_name',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='order',
            name='car_tag',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
