# Generated by Django 4.2.2 on 2023-07-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_link_user_alter_order_car_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fel_name',
            field=models.CharField(max_length=3000),
        ),
    ]
