# Generated by Django 4.2.2 on 2023-07-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_order_fel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='days_begin',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='order',
            name='days_end',
            field=models.CharField(max_length=3000),
        ),
    ]
